Added two papers
TheShadow29/awesome-grounding pull request #4
Opened 2019-08-23 06:45 UTC by ChopinSharp

Added two papers regarding referring expression segmentation.

2019-08-23 17:16 UTC, TheShadow29 requested changes
Thank you for your interest. The papers seem very relevant. Could you make the small changes I suggested, after that I can merge the pull request.

2019-08-23 17:16 UTC, TheShadow29 commented on README.md
> +1. Shi, Hengcan, et al. **Key-word-aware network for referring expression image segmentation.** Proceedings of the European Conference on Computer Vision (ECCV). 2018.[[http://openaccess.thecvf.com/c
Change it to ```[[Paper]](paper_link)```. Also, it seems they have a github repo (https://github.com/shihengcan/key-word-aware-network-pycaffe). You could add that using ```[[Code]](code_link)```

2019-08-23 17:16 UTC, TheShadow29 commented on README.md
> +1. Li, Ruiyu, et al. **Referring image segmentation via recurrent refinement networks.** Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2018.[[Paper]](http://openacces
For consistency please capitalize `code` to `Code`

2019-09-03 05:39 UTC, ChopinSharp commented
> Thank you for your interest. The papers seem very relevant. Could you make the small changes I suggested, after that I can merge the pull request.

Sorry for the late reply. I think i've made the changes as you requested. Please verify.

2019-09-03 15:08 UTC, merged

2019-09-03 15:09 UTC, TheShadow29 commented
Great! Thanks for your contribution! I have merged the changes.